package org.example;

import javax.swing.*;
        import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import java.awt.*;
        import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
        import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TaskTreeWhithoutPattern extends JFrame {

    // Класс для хранения узла дерева в памяти
    static class TaskNode extends DefaultMutableTreeNode {
        private final int id;
        private final String name;

        public TaskNode(int id, String name) {
            this.id = id;
            this.name = name;
        }

        public int getId() { return id; }

        @Override
        public String toString() {
            return name; // JTree отображает этот текст
        }
    }

    private JTree tree;
    private DefaultTreeModel treeModel;
    private DefaultMutableTreeNode virtualRoot;

    private JTextArea infoTextArea;
    private JButton btnCreate;
    private JButton btnDelete;

    private TaskNode selectedNode = null;

    public TaskTreeWhithoutPattern() {
        setTitle("Управление задачами (Полная загрузка)");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        initDatabase();
        initUI();
        buildEntireTree(); // Загружаем всё дерево сразу
    }

    private void initUI() {
        // Левая часть: Дерево
        virtualRoot = new DefaultMutableTreeNode("Root");
        treeModel = new DefaultTreeModel(virtualRoot);
        tree = new JTree(treeModel);
        tree.setRootVisible(false); // Скрываем невидимый корень
        tree.setShowsRootHandles(true);

        // Обработка кликов: только загрузка Info и сворачивание при повторном клике
        tree.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                TreePath path = tree.getPathForLocation(e.getX(), e.getY());

                if (path == null) {
                    clearSelection();
                    return;
                }

                Object component = path.getLastPathComponent();
                if (component instanceof TaskNode) {
                    TaskNode clickedNode = (TaskNode) component;

                    // Повторный клик — сворачиваем и снимаем выделение
                    if (tree.isPathSelected(path) && selectedNode == clickedNode) {
                        SwingUtilities.invokeLater(() -> {
                            tree.clearSelection();
                            tree.collapsePath(path);
                            clearSelection();
                        });
                    } else {
                        // Выбор узла — точечно запрашиваем Info
                        selectedNode = clickedNode;
                        btnDelete.setEnabled(true);
                        loadTaskInfo(selectedNode.getId());
                    }
                }
            }
        });

        // Правая часть: UI
        JPanel rightPanel = new JPanel(new BorderLayout());
        infoTextArea = new JTextArea();
        infoTextArea.setEditable(false);
        infoTextArea.setBorder(BorderFactory.createTitledBorder("Информация о задаче"));

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        btnCreate = new JButton("Создать задачу");
        btnDelete = new JButton("Удалить задачу");
        btnDelete.setEnabled(false);

        buttonPanel.add(btnCreate);
        buttonPanel.add(btnDelete);
        rightPanel.add(new JScrollPane(infoTextArea), BorderLayout.CENTER);
        rightPanel.add(buttonPanel, BorderLayout.SOUTH);

        btnCreate.addActionListener(e -> onCreateTask());
        btnDelete.addActionListener(e -> onDeleteTask());

        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, new JScrollPane(tree), rightPanel);
        splitPane.setDividerLocation(300);
        add(splitPane);
    }

    private void clearSelection() {
        selectedNode = null;
        infoTextArea.setText("");
        btnDelete.setEnabled(false);
    }

    // --- Блок работы с БД (H2) ---

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection("jdbc:h2:./tasks;AUTO_SERVER=TRUE");
    }

    private void initDatabase() {
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS tasks (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "parent_id INT," +
                    "name VARCHAR(255) NOT NULL," +
                    "info CLOB)");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Полная загрузка структуры дерева за ОДИН запрос к БД
    private void buildEntireTree() {
        virtualRoot.removeAllChildren();

        // Вспомогательная структура для быстрой сборки дерева в памяти
        Map<Integer, TaskNode> allNodes = new HashMap<>();
        List<Object[]> relations = new ArrayList<>(); // Хранит пары {childNode, parentId}

        String sql = "SELECT id, parent_id, name FROM tasks";

        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            // Шаг 1: Читаем все строки и создаем объекты узлов
            while (rs.next()) {
                int id = rs.getInt("id");
                int parentId = rs.getInt("parent_id");
                boolean isParentNull = rs.wasNull(); // Проверяем, был ли parent_id NULL в БД
                String name = rs.getString("name");

                TaskNode node = new TaskNode(id, name);
                allNodes.put(id, node);

                relations.add(new Object[]{node, isParentNull ? null : parentId});
            }

            // Шаг 2: Связываем узлы между собой в памяти без повторных запросов к БД
            for (Object[] relation : relations) {
                TaskNode child = (TaskNode) relation[0];
                Integer parentId = (Integer) relation[1];

                if (parentId == null) {
                    // Это корневой элемент
                    virtualRoot.add(child);
                } else {
                    // Находим родителя в нашей карте и добавляем ему ребенка
                    TaskNode parent = allNodes.get(parentId);
                    if (parent != null) {
                        parent.add(child);
                    }
                }
            }

            treeModel.reload();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Загрузка поля Info при клике
    private void loadTaskInfo(int taskId) {
        String sql = "SELECT info FROM tasks WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, taskId);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    infoTextArea.setText(rs.getString("info"));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Создание задачи
    private void onCreateTask() {
        String name = JOptionPane.showInputDialog(this, "Введите название задачи:");
        if (name == null || name.trim().isEmpty()) return;

        String info = JOptionPane.showInputDialog(this, "Введите описание задачи (Info):");

        String sql = "INSERT INTO tasks (parent_id, name, info) VALUES (?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            if (selectedNode != null) {
                pstmt.setInt(1, selectedNode.getId());
            } else {
                pstmt.setNull(1, Types.INTEGER);
            }
            pstmt.setString(2, name);
            pstmt.setString(3, info);
            pstmt.executeUpdate();

            // Перестраиваем дерево полностью, так как ленивой загрузки нет
            buildEntireTree();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Удаление задачи и ее потомков
    private void onDeleteTask() {
        if (selectedNode == null) return;

        int confirm = JOptionPane.showConfirmDialog(this,
                "Вы уверены, что хотите удалить задачу и все её подзадачи?",
                "Удаление", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        try (Connection conn = getConnection()) {
            conn.setAutoCommit(false);
            try {
                deleteTaskRecursive(conn, selectedNode.getId());
                conn.commit();

                // Перестраиваем дерево в UI
                buildEntireTree();
                clearSelection();
            } catch (SQLException ex) {
                conn.rollback();
                throw ex;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void deleteTaskRecursive(Connection conn, int id) throws SQLException {
        List<Integer> childIds = new ArrayList<>();
        String selectSQL = "SELECT id FROM tasks WHERE parent_id = ?";
        try (PreparedStatement pstmt = conn.prepareStatement(selectSQL)) {
            pstmt.setInt(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    childIds.add(rs.getInt("id"));
                }
            }
        }

        for (int childId : childIds) {
            deleteTaskRecursive(conn, childId);
        }

        String deleteSQL = "DELETE FROM tasks WHERE id = ?";
        try (PreparedStatement pstmt = conn.prepareStatement(deleteSQL)) {
            pstmt.setInt(1, id);
            pstmt.executeUpdate();
        }
    }

    public static void main(String[] args) {
        try { UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); } catch (Exception ignored) {}
        SwingUtilities.invokeLater(() -> new TaskTreeWhithoutPattern().setVisible(true));
    }
}
